apiVersion: v1
kind: ConfigMap
metadata:
  name: lwm2m-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: LwM2M Device
    driverImage: lwm2m-device:v0.0.1
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: 8
    instructions:
      read_value:
        gatewayPropertyList:
          ObjectId: /3442/0/130
          DataType: float
  leshanConfig: |
    serverUrl: coap://leshan-service.deviceshifu.svc.cluster.local:5683
