apiVersion: v1
kind: Service
metadata:
  labels:
    app: lwm2m
  name: lwm2m
  namespace: devices
spec:
  ports:
    - port: 11111
      protocol: TCP
      targetPort: 11111
  selector:
    app: lwm2m
  type: LoadBalancer
