apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-lwm2m
  namespace: devices
spec:
  sku: "LwM2M Device"
  connection: Ethernet
  address: lwm2m.devices.svc.cluster.local:11111
  protocol: HTTP
  gatewaySettings:
    protocol: lwm2m
    address: coap://leshan.eclipseprojects.io:5683
    LwM2MSetting:
      endpointName: leshan-client
      securityMode: None
